### ISSUE TITLE
Last edit date

### ISSUE THREAD

**Issue by Marcus6275** [HACManchester/documentation#10]
With the plan to improve and update the documentation of the space should we add a 'Last edited' and/or 'Last checked' date to the pages so that users can see whether the information on the page is up to date. 

I don't have the knowledge of how to implement such a thing but it would be useful to know without having to look at the code/github.

**Comment by grbd** [comment]
Everything under github is changed / added / removed as part of a commit. Since git originally was intended for software change control.
If you click on a file in github, then on "history" at the top right it should show all the changes that have been made to that file in order along with the date / time of the latest one.

Not sure about "last checked" though unless you mean pull requests that people do sometimes to submit changes if they don't have direct write access to the repo.

**Comment by Marcus6275** [comment]
Yeah I understand the data is stored on github.  I asking if there is a way we put that data on to the page though so it appears when people read it on the normal doc.hacman page as not everybody is familiar with github

**Comment by jmacarthur** [comment]
Personally, I'd just put the date on manually when you have a significant change. If you use the git change time, you'll get a date change for a minor change like a typo correction, which isn't really useful.

**Comment by grbd** [comment]
There's a plugin here that does what you're looking for
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin

I just tried it out and it seems to work fine
I could edit this repo directly to add it in (since I originally added in a bunch of others when we first set this up) but I'll put it through as part of a pull request.

For info it looks like this (bottom right)
![image](https://user-images.githubusercontent.com/8965579/108608898-02a2b780-73c2-11eb-91df-94d4174bd2b3.png)

**Comment by rossyst** [comment]
@grbd that plugin doesn't seem to work as each page appears to have the last update date changed when you add or edit a page not just the page in question. Reopening this for now till we figure that out

**Comment by grbd** [comment]
I've just made a change which I think fixes it, in the plugin docs it mentions

> This plugin needs access to the last commit that touched a specific file to be able to retrieve the date. By default many build environments only retrieve the last commit, which means you might need to:
> github actions: set fetch_depth to 0

So I've just done that with .github/workflows/ci.yml
```
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

And now it's showing different dates on different pages, so I think it's working
